from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class RegistryIndexTests(unittest.TestCase):
    def test_committed_indexes_match_machine_registries(self) -> None:
        from development.tools.registry_indexes import validate_registry_indexes

        self.assertEqual([], validate_registry_indexes(ROOT))

    def test_modified_index_is_reported(self) -> None:
        from development.tools.registry_indexes import validate_registry_indexes

        with tempfile.TemporaryDirectory() as directory:
            copy = Path(directory) / "repo"
            import shutil

            shutil.copytree(ROOT, copy, ignore=shutil.ignore_patterns(".git", "dist", "*.egg-info"))
            path = copy / "skill/registry/workflows.md"
            path.write_text(path.read_text(encoding="utf-8") + "\nmanual drift\n", encoding="utf-8")

            errors = validate_registry_indexes(copy)

        self.assertTrue(
            any("skill/registry/workflows.md is out of date" in error for error in errors)
        )

    def test_write_command_regenerates_indexes(self) -> None:
        from development.tools.generate_registry_indexes import main

        with tempfile.TemporaryDirectory() as directory:
            copy = Path(directory) / "repo"
            import shutil

            shutil.copytree(ROOT, copy, ignore=shutil.ignore_patterns(".git", "dist", "*.egg-info"))
            path = copy / "skill/registry/reuse-catalogue.md"
            path.write_text("stale\n", encoding="utf-8")

            exit_code = main(["--repository-root", str(copy), "--write"])

            self.assertEqual(0, exit_code)
            self.assertIn("Generated by getdone-generate-indexes", path.read_text())


if __name__ == "__main__":
    unittest.main()
