from __future__ import annotations

import shutil
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class DocumentationSiteTests(unittest.TestCase):
    def test_generated_documentation_is_current(self) -> None:
        from development.tools.documentation_site import validate_documentation

        self.assertEqual([], validate_documentation(ROOT))

    def test_drift_is_reported_and_write_repairs_it(self) -> None:
        from development.tools.documentation_site import validate_documentation, write_documentation

        with tempfile.TemporaryDirectory() as directory:
            copy = Path(directory) / "repo"
            shutil.copytree(ROOT, copy, ignore=shutil.ignore_patterns(".git", "site", "*.egg-info"))
            target = copy / "site_docs/catalogue/workflows/index.md"
            target.write_text("stale\n", encoding="utf-8")

            self.assertTrue(validate_documentation(copy))
            write_documentation(copy)
            self.assertEqual([], validate_documentation(copy))

    def test_catalogue_is_generated_from_registry_metadata(self) -> None:
        text = (ROOT / "site_docs/catalogue/workflows/index.md").read_text(encoding="utf-8")
        self.assertIn("Architecture Design", text)
        self.assertIn("Regression-First Bug Fix", text)
        self.assertIn("Generated by python development/scripts/generate_docs.py", text)

    def test_template_and_adapter_catalogues_link_to_rendered_content(self) -> None:
        templates = (ROOT / "site_docs/catalogue/templates.md").read_text(encoding="utf-8")
        adapters = (ROOT / "site_docs/catalogue/adapters.md").read_text(encoding="utf-8")

        self.assertIn("template-content/", templates)
        self.assertIn("adapter-content/", adapters)

        template_page = next((ROOT / "site_docs/catalogue/template-content").glob("*.md"))
        adapter_page = next((ROOT / "site_docs/catalogue/adapter-content").glob("*.md"))
        for page in (template_page, adapter_page):
            text = page.read_text(encoding="utf-8")
            self.assertIn("## Rendered preview", text)
            self.assertIn("## Complete source", text)
            self.assertIn("Authoritative source:", text)

    def test_zensical_configuration_uses_dedicated_docs_directory(self) -> None:
        text = (ROOT / "zensical.toml").read_text(encoding="utf-8")
        self.assertIn('docs_dir = "site_docs"', text)
        self.assertIn('"catalogue/workflows/index.md"', text)

    def test_existing_project_adoption_guide_is_published(self) -> None:
        guide = ROOT / "site_docs/guides/adopting-existing-project.md"
        self.assertTrue(guide.is_file())
        text = guide.read_text(encoding="utf-8")
        self.assertIn("Migrate current state, not all history", text)
        self.assertIn("getdone planning-prompt --mode project", text)

        config = (ROOT / "zensical.toml").read_text(encoding="utf-8")
        self.assertIn('"guides/adopting-existing-project.md"', config)


if __name__ == "__main__":
    unittest.main()
