"""Generate the Zensical documentation catalogue from product registries."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from getdone.frontmatter import parse_frontmatter

GENERATED_NOTICE = "<!-- Generated by python development/scripts/generate_docs.py. Do not edit directly. -->\n"


@dataclass(frozen=True)
class GeneratedPage:
    relative_path: Path
    content: str


def _load_json(root: Path, relative_path: str) -> dict[str, Any]:
    return json.loads((root / relative_path).read_text(encoding="utf-8"))


def _frontmatter(title: str, description: str, tags: Iterable[str]) -> str:
    rendered_tags = ", ".join(f'"{tag}"' for tag in tags)
    return (
        "---\n"
        f'title: "{title}"\n'
        f'description: "{description.replace(chr(34), chr(39))}"\n'
        f"tags: [{rendered_tags}]\n"
        "---\n\n"
    )


def _slug(identifier: str) -> str:
    return identifier.replace(".", "-").replace("_", "-")


def _workflow_pages(root: Path) -> list[GeneratedPage]:
    registry = _load_json(root, "skill/registry/workflows.json")
    workflows = sorted(registry["workflows"], key=lambda item: item["id"])
    index_lines = [
        GENERATED_NOTICE,
        _frontmatter("Workflows", "Executable development procedures selected by the workflow router.", ["catalogue", "workflows"]),
        "# Workflows\n",
        "Workflows define the procedure an agent follows. The router selects one primary workflow and adds specialist workflows only when their trigger applies.\n",
        "| Workflow | Purpose | Status |\n|---|---|---|\n",
    ]
    pages: list[GeneratedPage] = []
    for item in workflows:
        slug = _slug(item["id"])
        index_lines.append(
            f'| [{item["title"]}]({slug}.md) | {item["summary"]} | `{item["status"]}` |\n'
        )
        languages = ", ".join(f"`{language}`" for language in item.get("languages", []))
        aliases = ", ".join(f"`{alias}`" for alias in item.get("aliases", [])) or "None"
        tags = ", ".join(f"`{tag}`" for tag in item.get("tags", [])) or "None"
        body = (
            GENERATED_NOTICE
            + _frontmatter(item["title"], item["summary"], ["workflow", *item.get("tags", [])])
            + f"# {item['title']}\n\n"
            + f"**Stable ID:** `{item['id']}`  \n"
            + f"**Status:** `{item['status']}`  \n"
            + f"**Introduced:** `{item['introduced_in']}`  \n"
            + f"**Source:** `{item['path']}`\n\n"
            + "## Purpose\n\n"
            + item["summary"]
            + "\n\n## Applicability\n\n"
            + f"- **Languages:** {languages}\n"
            + f"- **Tags:** {tags}\n"
            + f"- **Aliases:** {aliases}\n"
        )
        if item.get("deprecated_in"):
            body += (
                "\n## Lifecycle\n\n"
                f"Deprecated in `{item['deprecated_in']}`. Replacement: `{item.get('replaced_by') or 'none'}`.\n"
            )
        pages.append(GeneratedPage(Path("catalogue/workflows") / f"{slug}.md", body))
    pages.append(GeneratedPage(Path("catalogue/workflows/index.md"), "".join(index_lines)))
    return pages


def _reuse_pages(root: Path) -> list[GeneratedPage]:
    catalogue = _load_json(root, "skill/registry/reuse-catalogue.json")
    entries = sorted(catalogue["entries"], key=lambda item: item["id"])
    by_kind: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        by_kind.setdefault(entry["kind"], []).append(entry)
    index = [
        GENERATED_NOTICE,
        _frontmatter("Reusable skills", "Reusable components, patterns, decisions, and references.", ["catalogue", "reuse"]),
        "# Reusable skills\n\n",
        "These entries help agents reuse established boundaries and patterns instead of inventing new ones.\n",
    ]
    pages: list[GeneratedPage] = []
    for kind, kind_entries in sorted(by_kind.items()):
        index.append(f"\n## {kind.replace('-', ' ').title()}\n\n")
        index.append("| Entry | Purpose | Status |\n|---|---|---|\n")
        for entry in kind_entries:
            slug = _slug(entry["id"])
            index.append(
                f'| [{entry["title"]}]({slug}.md) | {entry["summary"]} | `{entry["status"]}` |\n'
            )
            use_when = "\n".join(f"- {value}" for value in entry.get("use_when", [])) or "- No additional trigger recorded."
            avoid_when = "\n".join(f"- {value}" for value in entry.get("avoid_when", [])) or "- No explicit exclusion recorded."
            related = ", ".join(f"`{value}`" for value in entry.get("related", [])) or "None"
            languages = ", ".join(f"`{value}`" for value in entry.get("languages", []))
            body = (
                GENERATED_NOTICE
                + _frontmatter(entry["title"], entry["summary"], ["reuse", entry["kind"], *entry.get("tags", [])])
                + f"# {entry['title']}\n\n"
                + f"**Stable ID:** `{entry['id']}`  \n"
                + f"**Kind:** `{entry['kind']}`  \n"
                + f"**Status:** `{entry['status']}`  \n"
                + f"**Source:** `{entry['path']}`\n\n"
                + "## Purpose\n\n"
                + entry["summary"]
                + "\n\n## Use when\n\n"
                + use_when
                + "\n\n## Avoid when\n\n"
                + avoid_when
                + "\n\n## Applicability\n\n"
                + f"- **Languages:** {languages}\n"
                + f"- **Related entries:** {related}\n"
            )
            pages.append(GeneratedPage(Path("catalogue/reuse") / f"{slug}.md", body))
    pages.append(GeneratedPage(Path("catalogue/reuse/index.md"), "".join(index)))
    return pages


def _source_slug(path: Path) -> str:
    relative = path.as_posix().removesuffix(".md")
    return relative.replace("/", "--").replace(".", "-").lower()


def _source_content_page(
    root: Path,
    path: Path,
    *,
    title: str,
    description: str,
    destination_root: str,
) -> GeneratedPage:
    rel = path.relative_to(root).as_posix()
    source = path.read_text(encoding="utf-8")
    parsed = parse_frontmatter(source)
    preview = parsed.body.strip()
    metadata = ""
    if parsed.data:
        metadata_rows = "".join(
            f"| `{key}` | `{value}` |\n" for key, value in sorted(parsed.data.items())
        )
        metadata = "## Template metadata\n\n| Field | Value |\n|---|---|\n" + metadata_rows + "\n"
    body = (
        GENERATED_NOTICE
        + _frontmatter(title, description, ["catalogue", "source-content"])
        + f"# {title}\n\n"
        + f"Authoritative source: `{rel}`\n\n"
        + metadata
        + "## Rendered preview\n\n"
        + preview
        + "\n\n## Complete source\n\n```markdown\n"
        + source.rstrip()
        + "\n```\n"
    )
    return GeneratedPage(Path(destination_root) / f"{_source_slug(path.relative_to(root))}.md", body)


def _content_inventory_pages(
    root: Path,
    title: str,
    description: str,
    source_glob: str,
    relative_path: str,
    destination_root: str,
) -> list[GeneratedPage]:
    rows: list[str] = []
    pages: list[GeneratedPage] = []
    for path in sorted(root.glob(source_glob)):
        if path.name.lower() in {"readme.md", "index.md"}:
            continue
        rel = path.relative_to(root).as_posix()
        source = path.read_text(encoding="utf-8")
        heading = next(
            (line.removeprefix("# ").strip() for line in source.splitlines() if line.startswith("# ")),
            path.stem.replace("-", " ").title(),
        )
        content_page = _source_content_page(
            root, path, title=heading, description=f"Rendered content for {rel}.", destination_root=destination_root
        )
        pages.append(content_page)
        link = content_page.relative_path.relative_to(Path(relative_path).parent).as_posix()
        rows.append(f"| [{heading}]({link}) | `{rel}` |\n")
    body = (
        GENERATED_NOTICE
        + _frontmatter(title, description, ["catalogue"])
        + f"# {title}\n\n{description} Each item links to a rendered preview and its complete source.\n\n"
        + "| Item | Authoritative source |\n|---|---|\n"
        + "".join(rows)
    )
    return [GeneratedPage(Path(relative_path), body), *pages]


def _simple_inventory_page(root: Path, title: str, description: str, source_glob: str, relative_path: str) -> GeneratedPage:
    rows: list[str] = []
    for path in sorted(root.glob(source_glob)):
        if path.name.lower() in {"readme.md", "index.md"}:
            continue
        rel = path.relative_to(root).as_posix()
        heading = next(
            (line.removeprefix("# ").strip() for line in path.read_text(encoding="utf-8").splitlines() if line.startswith("# ")),
            path.stem.replace("-", " ").title(),
        )
        rows.append(f"| {heading} | `{rel}` |\n")
    body = (
        GENERATED_NOTICE
        + _frontmatter(title, description, ["catalogue"])
        + f"# {title}\n\n{description}\n\n"
        + "| Item | Authoritative source |\n|---|---|\n"
        + "".join(rows)
    )
    return GeneratedPage(Path(relative_path), body)


def _cli_page(root: Path) -> GeneratedPage:
    contracts = _load_json(root, "skill/contracts/public-contracts.json")
    rows = "".join(f"| `{command}` | Installed console entry point |\n" for command in contracts["cli_commands"])
    body = (
        GENERATED_NOTICE
        + _frontmatter("CLI reference", "Installed commands and their stable public contract.", ["reference", "cli"])
        + "# CLI reference\n\n"
        + "All commands use exit code `0` for success, `1` for validation or operational failure, and `2` for command-line usage errors.\n\n"
        + "| Command | Purpose |\n|---|---|\n"
        + rows
        + "\nRun any command with `--help` for its exact arguments.\n"
    )
    return GeneratedPage(Path("reference/cli.md"), body)


def _catalogue_home() -> GeneratedPage:
    body = (
        _frontmatter("Skills catalogue", "Browse workflows, reusable skills, standards, policies, templates, adapters, and schemas.", ["catalogue"])
        + "# Skills catalogue\n\n"
        + "The catalogue is generated from authoritative registries and repository inventories. Generated pages must not be edited directly.\n\n"
        + "- [Workflows](workflows/index.md): executable development procedures.\n"
        + "- [Reusable skills](reuse/index.md): shared components, patterns, and decision references.\n"
        + "- [Language standards](languages.md): language-specific engineering expectations.\n"
        + "- [Policies](policies.md): mandatory behavioural and governance rules.\n"
        + "- [Templates](templates.md): project records and governance templates.\n"
        + "- [Adapters](adapters.md): agent integration guidance.\n"
        + "- [Schemas](schemas.md): machine-readable public contracts.\n"
    )
    return GeneratedPage(Path("catalogue/index.md"), body)


def generate_pages(root: Path) -> list[GeneratedPage]:
    pages = [_catalogue_home(), _cli_page(root)]
    pages.extend(_workflow_pages(root))
    pages.extend(_reuse_pages(root))
    pages.extend(
        [
            _simple_inventory_page(root, "Language standards", "Engineering standards selected by implementation language.", "skill/standards/languages/*.md", "catalogue/languages.md"),
            _simple_inventory_page(root, "Policies", "Mandatory policies loaded when their trigger applies.", "skill/policies/*.md", "catalogue/policies.md"),
            *_content_inventory_pages(root, "Templates", "Bootstrap and governance templates copied or instantiated by projects.", "skill/**/templates/**/*.md", "catalogue/templates.md", "catalogue/template-content"),
            *_content_inventory_pages(root, "Adapters", "Guidance and managed files for supported coding-agent environments.", "skill/adapters/*.md", "catalogue/adapters.md", "catalogue/adapter-content"),
            _simple_inventory_page(root, "Schemas", "JSON schemas that define machine-readable public contracts.", "skill/schemas/*.json", "catalogue/schemas.md"),
        ]
    )
    return pages


def write_documentation(root: Path) -> list[Path]:
    docs_root = root / "site_docs"
    written: list[Path] = []
    for page in generate_pages(root):
        destination = docs_root / page.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(page.content, encoding="utf-8")
        written.append(destination)
    return written


def validate_documentation(root: Path) -> list[str]:
    errors: list[str] = []
    docs_root = root / "site_docs"
    for page in generate_pages(root):
        destination = docs_root / page.relative_path
        if not destination.exists():
            errors.append(f"{destination.relative_to(root)} is missing; run python development/scripts/generate_docs.py --write")
        elif destination.read_text(encoding="utf-8") != page.content:
            errors.append(f"{destination.relative_to(root)} is out of date; run python development/scripts/generate_docs.py --write")
    return errors
