"""Render and validate human-readable registry indexes."""

from __future__ import annotations

from pathlib import Path

try:
    from getdone.catalogue import Catalogue, CatalogueEntry, WorkflowSpec, load_catalogue
except ModuleNotFoundError as exc:  # Direct execution from the tooling directory.
    if exc.name not in {"getdone", "getdone.catalogue"}:
        raise
    from catalogue import Catalogue, CatalogueEntry, WorkflowSpec, load_catalogue

GENERATED_MARKER = "<!-- Generated by getdone-generate-indexes. Do not edit by hand. -->"
WORKFLOW_INDEX = Path("skill/registry/workflows.md")
REUSE_INDEX = Path("skill/registry/reuse-catalogue.md")


def _display(values: tuple[str, ...]) -> str:
    return "<br>".join(f"`{value}`" for value in values) if values else "—"


def _replacement(value: str | None) -> str:
    return "—" if value is None else f"`{value}`"


def _workflow_row(item: WorkflowSpec) -> str:
    return (
        f"| `{item.workflow_id}` | {item.title} | `{item.path.as_posix()}` | "
        f"{item.status} | {item.introduced_in} | {_display(item.aliases)} | "
        f"{_replacement(item.replaced_by)} |"
    )


def render_workflow_index(catalogue: Catalogue) -> str:
    lines = [
        "# Workflow Registry",
        "",
        GENERATED_MARKER,
        "",
        f"Registry contract version: `{catalogue.workflow_registry_version}`.",
        "Canonical workflow instructions remain in `skill/workflows/`.",
        "",
        "| ID | Title | Path | Status | Introduced | Aliases | Replacement |",
        "|---|---|---|---|---|---|---|",
    ]
    ordered = sorted(catalogue.workflows, key=lambda item: item.workflow_id)
    lines.extend(_workflow_row(item) for item in ordered)
    return "\n".join(lines) + "\n"


def _reuse_row(item: CatalogueEntry) -> str:
    return (
        f"| `{item.entry_id}` | {item.kind} | {item.title} | `{item.path.as_posix()}` | "
        f"{item.status} | {item.introduced_in} | {_display(item.aliases)} | "
        f"{_replacement(item.replaced_by)} |"
    )


def render_reuse_index(catalogue: Catalogue) -> str:
    lines = [
        "# Reuse Catalogue Registry",
        "",
        GENERATED_MARKER,
        "",
        f"Catalogue contract version: `{catalogue.version}`.",
        "Use `getdone-search` for ranked task-oriented discovery.",
        "",
        "| ID | Kind | Title | Path | Status | Introduced | Aliases | Replacement |",
        "|---|---|---|---|---|---|---|---|",
    ]
    core = (item for item in catalogue.entries if item.source == "core")
    lines.extend(_reuse_row(item) for item in sorted(core, key=lambda x: x.entry_id))
    return "\n".join(lines) + "\n"


def rendered_indexes(root: Path) -> dict[Path, str]:
    catalogue = load_catalogue(root)
    return {
        WORKFLOW_INDEX: render_workflow_index(catalogue),
        REUSE_INDEX: render_reuse_index(catalogue),
    }


def write_registry_indexes(root: Path) -> tuple[Path, ...]:
    written: list[Path] = []
    for relative, content in rendered_indexes(root).items():
        path = root / relative
        path.write_text(content, encoding="utf-8")
        written.append(relative)
    return tuple(written)


def validate_registry_indexes(root: Path) -> list[str]:
    errors: list[str] = []
    for relative, expected in rendered_indexes(root).items():
        path = root / relative
        if not path.is_file():
            errors.append(f"{relative.as_posix()} is missing")
        elif path.read_text(encoding="utf-8") != expected:
            errors.append(f"{relative.as_posix()} is out of date")
    return errors
